/*
 * This file was generated by generate_typesystem.py.
 */
#ifndef __RS_HSRB_PERCEPTION_ALL_TYPES_H__
#define __RS_HSRB_PERCEPTION_ALL_TYPES_H__

#include <rs_hsrb_perception/types/type_definitions.h>


#endif /* __RS_HSRB_PERCEPTION_ALL_TYPES_H__ */
