/*
 * This file was generated by generate_typesystem.py.
 * Filename:    property_types
 * Name:        property
 * Description: No description given
 * Version:     1.0
 * Vendor:      None
 */
#ifndef __PROPERTY_TYPES_H__
#define __PROPERTY_TYPES_H__

#include <rs/feature_structure_proxy.h>
#include <rs_hsrb_perception/types/type_definitions.h>
#include <rs/types/core_types.h>

namespace rs_hsrb_perception
{

/*
 * No description given
 */
class BoundingBox : public rs::Annotation
{
private:
  void initFields()
  {
    width.init(this, "width");
    height.init(this, "height");
    depth.init(this, "depth");
  }
public:
  // No description given
  rs::FeatureStructureEntry<float> width;
  // No description given
  rs::FeatureStructureEntry<float> height;
  // No description given
  rs::FeatureStructureEntry<float> depth;

  BoundingBox(const BoundingBox &other) :
      rs::Annotation(other)
  {
    initFields();
  }

  BoundingBox(uima::FeatureStructure fs) :
      rs::Annotation(fs)
  {
    initFields();
  }
};

}

TYPE_TRAIT(rs_hsrb_perception::BoundingBox, RS_HSRB_PERCEPTION_PROPERTY_BOUNDINGBOX)

#endif /* __PROPERTY_TYPES_H__ */
