/*
 * This file was generated by generate_typesystem.py.
 */
#ifndef __RS_HSRB_PERCEPTION_TYPE_DEFINITIONS_H__
#define __RS_HSRB_PERCEPTION_TYPE_DEFINITIONS_H__

#define RS_HSRB_PERCEPTION_PROPERTY_BOUNDINGBOX "rs_hsrb_perception.property.BoundingBox"

#endif /* __RS_HSRB_PERCEPTION_TYPE_DEFINITIONS_H__ */
