%YAML:1.0
names:
   - robocup_table
   - robocup_shelf
robocup_table:
   type: Table
   width:  0.8
   height: 0.717
   depth: 0.8
   transform: !!opencv-matrix
      rows: 4
      cols: 4
      dt: d
      data: [ 1., 0., 0., 0.7,
              0., 1., 0., 0.,
              0., 0., 1., 0.4,
              0., 0., 0., 1. ]
robocup_shelf:
   type: Shelf
   width:  0.5
   height: 2.0
   depth: 1.0
   transform: !!opencv-matrix
      rows: 4
      cols: 4
      dt: d
      data: [ 1., 0., 0., 0.,
              0., 1., 0., -0.4,
              0., 0., 1., 0.8,
              0., 0., 0., 1. ]